In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import files
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


In [3]:
df_ques_cluster = pd.read_csv('/drive/My Drive/Research Project IIT-I/AP Question clusters.csv')

In [4]:
df_ques_cluster

index    BlockName      Category  Year  Month  Day  \
0      23781986   SARAVAKOTA        Others  2020      6   10   
1      23824164      NELLORE        Others  2020      3   17   
2      23824118    KODAVALUR  Green Manure  2020      3   16   
3      23824098    MARRIPADU        Others  2020      3   15   
4      23821955     MANUBOLU        Others  2020      1   25   
...         ...          ...           ...   ...    ...  ...   
26714  23825672    CHILLAKUR      Oilseeds  2020     10   23   
26715  23825977  VENKATAGIRI      Oilseeds  2020     11   12   
26716  23823419        RAPUR        Fruits  2020      2   25   
26717  23824455  BALAYAPALLE        Fruits  2020      7    6   
26718  23823420        RAPUR        Fruits  2020      2   25   

                               Crop DistrictName                  QueryType  \
0                            Others   SRIKAKULAM         Government Schemes   
1                            Others      NELLORE                      Seeds   
2        KolanchiTephrosia Purpurea      NELLORE                  Varieties   
3                            Others      NELLORE         Government Schemes   
4                            Others      NELLORE         Government Schemes   
...                             ...          ...                        ...   
26714  Groundnut pea nutmung phalli      NELLORE                      Seeds   
26715  Groundnut pea nutmung phalli      NELLORE                      Seeds   
26716                        Citrus      NELLORE  Agriculture Mechanization   
26717                        Citrus      NELLORE           Plant Protection   
26718                        Citrus      NELLORE        Nutrient Management   

             Sector       StateName                     QueryText  \
0       AGRICULTURE  ANDHRA PRADESH                    MAO NUMBER   
1       AGRICULTURE  ANDHRA PRADESH                    MAO NUMBER   
2       AGRICULTURE  ANDHRA PRADESH                    MAO NUMBER   
3       AGRICULTURE  ANDHRA PRADESH                    MAO NUMBER   
4       AGRICULTURE  ANDHRA PRADESH                    MAO NUMBER   
...             ...             ...                           ...   
26714   AGRICULTURE  ANDHRA PRADESH          GROUNDS NUT VARIETY    
26715   AGRICULTURE  ANDHRA PRADESH  kadiri ground nut varieties    
26716  HORTICULTURE  ANDHRA PRADESH       CITRUS Scab MANAGEMENT    
26717  HORTICULTURE  ANDHRA PRADESH        CITRUS SCAB MANAGEMENT   
26718  HORTICULTURE  ANDHRA PRADESH        CITRUS Scab MANAGEMENT   

                                                  KccAns  Cluster  
0                   -- RECOMMENDED TO CONTACT 8886612698        1  
1                                          -- 8886613101        1  
2                                             8886613686        1  
3                                             8886613671        1  
4                                   MAO NUMBER8886613708        1  
...                                                  ...      ...  
26714               -- RECOMMENDED TO CONTACT 9989628385      568  
26715  Agricultural Research Station Kadiri - 515 591...      568  
26716  recommended to spray amistar top azoxystrobind...      569  
26717  RECOMMENDED TO SPRAY CARBENDAZIM BAVISTIN 2GM ...      569  
26718  recommended to spray amistar top azoxystrobind...      569  

[26719 rows x 14 columns]

In [5]:
labels = pd.get_dummies(df_ques_cluster.Cluster)

In [6]:
labels

1    2    3    4    5    6    7    8    9    10   ...  560  561  562  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
26714    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
26715    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
26716    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
26717    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
26718    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       563  564  565  566  567  568  569  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
26714    0    0    0    0    0    1    0  
26715    0    0    0    0    0    1    0  
26716    0    0    0    0    0    0    1  
26717    0    0    0    0    0    0    1  
26718    0    0    0    0    0    0    1  

[26719 rows x 569 columns]

In [7]:
pip install sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 5.3 MB/s 
     |████████████████████████████████| 5.5 MB 39.8 MB/s 
     |████████████████████████████████| 1.3 MB 56.1 MB/s 
     |████████████████████████████████| 182 kB 65.5 MB/s 
     |████████████████████████████████| 7.6 MB 53.6 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=5dab63c07e61541a7d25418a8e2502e91ab9821d54513c6cba1cb2ebae47f227
  Stored in directory: /root/.cache/pip/wheels/bf/06/fb/d59c1e5bd1dac7f6cf61ec0036cc3a10ab8fecaa6b2c3d3ee9
Successfully built sentence-transformers


In [8]:
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

In [9]:
sentence_embeddings = sbert_model.encode(df_ques_cluster.QueryText)

In [10]:
sentence_embeddings

array([[-0.2498262 , -0.06988434,  0.5104995 , ..., -0.07754841,
        -0.28346765,  0.18747021],
       [-0.2498262 , -0.06988434,  0.5104995 , ..., -0.07754841,
        -0.28346765,  0.18747021],
       [-0.2498262 , -0.06988434,  0.5104995 , ..., -0.07754841,
        -0.28346765,  0.18747021],
       ...,
       [ 0.18587734,  0.26502147,  0.18996672, ...,  0.54467624,
        -0.34343442, -0.5994816 ],
       [ 0.18587734,  0.26502147,  0.18996672, ...,  0.54467624,
        -0.34343442, -0.5994816 ],
       [ 0.18587738,  0.26502216,  0.18996744, ...,  0.544676  ,
        -0.3434346 , -0.59948176]], dtype=float32)

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(sentence_embeddings, labels, test_size = 0.2, random_state = 42)

In [13]:
X_train.shape

(21375, 768)

In [14]:
X_train

array([[-0.5623451 , -0.7238392 , -0.4385938 , ...,  0.21972224,
        -0.2342044 ,  0.20387591],
       [ 0.30686316,  0.09977397,  1.3167244 , ..., -0.47966337,
        -0.55457515, -0.1393763 ],
       [-0.46014872,  0.2117085 ,  0.954776  , ...,  0.7694585 ,
         0.08209138, -0.1254217 ],
       ...,
       [-0.43640468, -0.0047852 ,  0.3221785 , ..., -0.00850349,
        -0.47308755, -0.5984331 ],
       [-0.2370112 ,  0.22151017,  0.9652733 , ...,  0.18735912,
        -0.38761416, -0.16776037],
       [-0.10036709,  0.14940493,  1.3858415 , ...,  0.3047846 ,
        -0.2989447 , -0.10187565]], dtype=float32)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
model = LogisticRegression()
model.fit(X_train, np.array([(np.argmax(x)+1) for x in np.array(y_train)]))

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [17]:
y_pred = model.predict(X_test)

In [18]:
y_pred

array([ 78,   5,  66, ..., 107,  64, 287])

In [19]:
actual = [(np.argmax(x)+1) for x in np.array(y_test)]
actual = np.array(actual)

In [20]:
actual

array([ 78,   5,  66, ..., 107,  64, 287])

In [21]:
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

print('weighted', precision_recall_fscore_support(actual, y_pred, average='weighted'))
print('micro',precision_recall_fscore_support(actual, y_pred, average='micro'))
print('macro',precision_recall_fscore_support(actual, y_pred, average='macro'))
print('accuracy', accuracy_score(actual, y_pred))

weighted (0.9633688214364153, 0.9711826347305389, 0.9652475130254893, None)
micro (0.9711826347305389, 0.9711826347305389, 0.9711826347305389, None)
macro (0.8240337990143657, 0.8115291324415707, 0.8083883013578582, None)
accuracy 0.9711826347305389


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [23]:
model.score(X_test, np.array([(np.argmax(x)+1) for x in np.array(y_test)]))

0.9711826347305389